version: '3.7'
services:
  monerod:
    image: mainnetpat/monerod:v0.18.3.2
    entrypoint: [""]
    command: monerod --testnet --log-level=0 --no-igd --fixed-difficulty=1 --data-dir .localnet/xmr_local/node1 --disable-rpc-ban --db-sync-mode=safe --no-zmq --non-interactive --rpc-bind-ip=0.0.0.0 --rpc-bind-port=28081 --p2p-bind-ip=0.0.0.0 --p2p-bind-port=28080 --confirm-external-bind --rpc-ssl=disabled --rpc-access-control-origins="*" --add-exclusive-node monerod-peer:48080 --allow-local-ip
    ports:
      - '127.0.0.1:28081:28081'
    restart: unless-stopped
    volumes:
      - ./.localnet:/home/monero/.localnet

  monerod-peer:
    image: mainnetpat/monerod:v0.18.3.2
    entrypoint: [""]
    command: monerod --testnet --log-level=0 --no-igd --fixed-difficulty=1 --data-dir .localnet/xmr_local/node2 --disable-rpc-ban --db-sync-mode=safe --no-zmq --non-interactive --rpc-bind-ip=0.0.0.0 --rpc-bind-port=48081 --p2p-bind-ip=0.0.0.0 --p2p-bind-port=48080 --confirm-external-bind --rpc-ssl=disabled --rpc-access-control-origins="*" --add-exclusive-node monerod:28080 --allow-local-ip
    ports:
      - '127.0.0.1:48081:48081'
    restart: unless-stopped
    volumes:
      - ./.localnet:/home/monero/.localnet

  monero-wallet-rpc:
    image: mainnetpat/monerod:v0.18.3.2
    entrypoint: [""]
    command: monero-wallet-rpc --testnet --daemon-host=monerod --daemon-port=28081 --trusted-daemon --disable-rpc-ban --rpc-bind-ip=0.0.0.0 --rpc-bind-port=28084 --rpc-login=rpc_user:abc123  --confirm-external-bind --non-interactive --rpc-ssl=disabled --daemon-ssl=disabled --wallet-dir ./.localnet --rpc-access-control-origins="*"
    ports:
      - '127.0.0.1:28084:28084'
    volumes:
      - ./.localnet:/home/monero/.localnet
    restart: unless-stopped
